### PR TITLE
chore(deps): remove dash dependency

### PR DESCRIPTION
**Pull request by jMergenthal**
open question:
There is no need to publish to npm here. So, should we even add a new git tag for this? We could also just bring it to master, and just add it with the next upcoming release.

### CODE REVIEW

**Comment by danielkoch** [comment]
Normally removal of a feature would lead into a major next version. But I think in this case I would ignore it and create another bugfix version (also with a new npm version and git tag) because we will need to change the dependencies. This should also remove the vulnerabilities.

**Comment by ernscht** [comment]
No need for a new version or a tag at all.
(You changed only dev dependencies, it's not a feature removal fo end users)

**Comment by danielkoch** [comment]
Different opinions here: @jMergenthal: Please decide ;-)

**Review by ernscht — APPROVED** [review]
👌

**Review by danielkoch — APPROVED** [review]

**Comment by jMergenthal** [comment]
I think it's too small of a change to justify a new git tag, especially since this tool was hardly used at all anyways. As @ernscht correctly pointed out, nothing changes for the end user. Publishing this would essentially be a new package with no changes.
--> No publish, no new git tag.

**Pull request merged**
